
package ir.store.SOAP.Client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WebServiceInterface", targetNamespace = "http://Server.SOAP.store.ir/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebServiceInterface {


    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg5
     * @param arg4
     * @param arg1
     * @param arg0
     * @return
     *     returns ir.store.SOAP.Client.IntArray
     */
    @WebMethod
    @WebResult(partName = "return")
    public IntArray recieveLog(
        @WebParam(name = "arg0", partName = "arg0")
        IntArray arg0,
        @WebParam(name = "arg1", partName = "arg1")
        StringArray arg1,
        @WebParam(name = "arg2", partName = "arg2")
        StringArray arg2,
        @WebParam(name = "arg3", partName = "arg3")
        StringArray arg3,
        @WebParam(name = "arg4", partName = "arg4")
        StringArray arg4,
        @WebParam(name = "arg5", partName = "arg5")
        StringArray arg5);

}
